# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03a3f1bd5010217e341cbfa3f07e31dd2e3c41ff6af82ad2bd3bf926b5654ea580456f1cdcdce0200bfce4cb84155f4da1b57b632c81348cabe40a6ee7de564b

test:
  secret_key_base: 380758995de357606c6a38452db00373173b8ee1e610245e2268327f5a233ead0da76afc65978c0171597715689f87a1362987a943406716f7ca9fd89df8d8c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
